# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdbe0172d75344e9960aadd1b5eee4c088119869a9f9001d909ce54906153cd87d9570f0d44d8b322272bfc856a4be474e74f9dc9b21766e59da9d078bac7e81

test:
  secret_key_base: 3aec83e0e9c55fb713753baab4f71902527126af5b338fdcd5188e3a8a03ca5fe1a825cdd5cd171f985ae9dbf7cf37e77864218ae1a6b26d04d1e66e531a2ead

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
